import { eq, and } from "drizzle-orm";
import { db, userProfilesTable, weeklyRecapsTable } from "@workspace/db";
import { buildWeeklyAggregate, generateWeeklyRecap } from "./weeklyRecap";
import { getDateInTimezone } from "../routes/dashboard";
import { logger } from "./logger";

// Returns "HH:MM" in the given IANA timezone — mirrors the pattern in outboundCaller.ts.
function getCurrentTimeInTz(timezone: string): string {
  const now = new Date();
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).formatToParts(now);
  const hour = parts.find((p) => p.type === "hour")?.value ?? "00";
  const minute = parts.find((p) => p.type === "minute")?.value ?? "00";
  return `${hour.padStart(2, "0")}:${minute.padStart(2, "0")}`;
}

// Returns the ISO day-of-week (0 = Sunday) in the given timezone,
// derived from the YYYY-MM-DD local date so the anchor matches getDateInTimezone.
function getDayOfWeekInTz(tz: string): number {
  const dateStr = getDateInTimezone(tz);
  return new Date(dateStr + "T12:00:00Z").getUTCDay();
}

// Given the user's local Sunday (YYYY-MM-DD), returns that Mon–Sun week's bounds.
function weekBoundsForSunday(sunday: string): { weekStart: string; weekEnd: string } {
  const end = new Date(sunday + "T12:00:00Z");
  const start = new Date(end);
  start.setUTCDate(end.getUTCDate() - 6);
  const fmt = (x: Date): string => x.toISOString().split("T")[0]!;
  return { weekStart: fmt(start), weekEnd: fmt(end) };
}

async function runWeeklyRecapJob(): Promise<void> {
  const profiles = await db
    .select({ userId: userProfilesTable.userId, callTimezone: userProfilesTable.callTimezone })
    .from(userProfilesTable);

  for (const profile of profiles) {
    const tz = profile.callTimezone ?? "America/New_York";

    // Only fire on Sunday from 19:00 onwards in the user's timezone.
    // Using >= rather than === so a delayed 60s tick that lands at 19:01 still fires.
    // The DB existence check below is the sole dup guard — idempotency, not minute precision.
    if (getDayOfWeekInTz(tz) !== 0) continue;
    if (getCurrentTimeInTz(tz) < "19:00") continue;

    const userId = profile.userId;
    const today = getDateInTimezone(tz); // confirmed Sunday
    const { weekStart, weekEnd } = weekBoundsForSunday(today);

    // Skip if a recap for this week already exists (idempotent on re-run).
    const existing = await db
      .select({ id: weeklyRecapsTable.id })
      .from(weeklyRecapsTable)
      .where(and(eq(weeklyRecapsTable.userId, userId), eq(weeklyRecapsTable.weekStart, weekStart)))
      .limit(1);

    if (existing.length > 0) {
      logger.info({ userId, weekStart }, "Weekly recap cron: already exists, skipping");
      continue;
    }

    try {
      const aggregate = await buildWeeklyAggregate(userId, weekStart, weekEnd);
      await generateWeeklyRecap(userId, aggregate);
      // TODO: send push notification once APNs key is uploaded (see push deferred note)
      logger.info({ userId, weekStart }, "Weekly recap generated by cron");
    } catch (err) {
      logger.error({ err, userId, weekStart }, "Weekly recap cron: generation failed for user");
    }
  }
}

export function startWeeklyRecapJob(): void {
  const ONE_MINUTE_MS = 60 * 1000;
  // Track which wall-clock minute we last processed so a slow iteration
  // that overlaps the next tick doesn't double-fire for the same minute.
  let lastFiredMinute = "";

  setInterval(() => {
    const minuteKey = new Date().toISOString().slice(0, 16); // "YYYY-MM-DDTHH:MM"
    if (minuteKey === lastFiredMinute) return;
    lastFiredMinute = minuteKey;

    void runWeeklyRecapJob().catch((err: unknown) => {
      logger.error({ err }, "Weekly recap cron job failed");
    });
  }, ONE_MINUTE_MS);

  logger.info("Weekly recap job scheduled (Sunday 19:00 local, 1min poll)");
}
