import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import dailyLogsRouter from "./daily-logs";
import moodsRouter from "./moods";
import goalsRouter from "./goals";
import habitsRouter from "./habits";
import insightsRouter from "./insights";
import logEntriesRouter from "./log-entries";
import dashboardRouter from "./dashboard";
import vapiContextRouter from "./vapi-context";
import debriefRouter from "./debrief";
import settingsRouter from "./settings";
import vapiWebhookRouter from "./vapi-webhook";
import calendarEventsRouter from "./calendar-events";
import googleCalendarRouter from "./google-calendar";
import googleOAuthRouter from "./google-oauth";
import onboardingRouter from "./onboarding";
import analyzeImageRouter from "./analyze-image";
import profileRouter from "./profile";
import todayCardsRouter from "./todayCards";
import routinesRouter from "./routines";
import habitCompletionsRouter from "./habit-completions";
import catchUpRouter from "./catch-up";
import telemetryRouter from "./telemetry";
import mealRouter from "./meal";
import feedbackRouter from "./feedback";
import remindersRouter from "./reminders";
import personalDatesRouter from "./personal-dates";
import homeBriefingRouter from "./home-briefing";
import exercisesRouter from "./exercises";
import workoutRouter from "./workout";
import askRouter from "./ask";
import weeklyRecapRouter from "./weekly-recap";
import actionProposalsRouter from "./action-proposals";
import buddiesRouter from "./buddies";
import sharedCommitmentsRouter from "./shared-commitments";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(dailyLogsRouter);
router.use(moodsRouter);
router.use(goalsRouter);
router.use(habitsRouter);
router.use(insightsRouter);
router.use(logEntriesRouter);
router.use(dashboardRouter);
router.use(vapiContextRouter);
router.use(debriefRouter);
router.use(settingsRouter);
router.use(vapiWebhookRouter);
router.use(calendarEventsRouter);
router.use(googleCalendarRouter);
router.use(googleOAuthRouter);
router.use(onboardingRouter);
router.use(analyzeImageRouter);
router.use(profileRouter);
router.use(todayCardsRouter);
router.use(routinesRouter);
router.use(habitCompletionsRouter);
router.use(catchUpRouter);
router.use(telemetryRouter);
router.use(mealRouter);
router.use(feedbackRouter);
router.use(remindersRouter);
router.use(personalDatesRouter);
router.use(homeBriefingRouter);
router.use(exercisesRouter);
router.use(workoutRouter);
router.use(askRouter);
router.use(weeklyRecapRouter);
router.use(actionProposalsRouter);
router.use(buddiesRouter);
router.use(sharedCommitmentsRouter);

export default router;
