// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/plan/PlanCreateSheet.tsx": () => import("../components/mockups/plan/PlanCreateSheet.tsx"),
  "./components/mockups/shell/Calendar.tsx": () => import("../components/mockups/shell/Calendar.tsx"),
  "./components/mockups/shell/Countdown.tsx": () => import("../components/mockups/shell/Countdown.tsx"),
  "./components/mockups/shell/PlanLibrary.tsx": () => import("../components/mockups/shell/PlanLibrary.tsx"),
  "./components/mockups/shell/PlanScreen.tsx": () => import("../components/mockups/shell/PlanScreen.tsx"),
  "./components/mockups/shell/ThisWeek.tsx": () => import("../components/mockups/shell/ThisWeek.tsx"),
  "./components/mockups/today-cards/GoalProgress.tsx": () => import("../components/mockups/today-cards/GoalProgress.tsx"),
  "./components/mockups/today-cards/Motivation.tsx": () => import("../components/mockups/today-cards/Motivation.tsx"),
  "./components/mockups/today-cards/Recovery.tsx": () => import("../components/mockups/today-cards/Recovery.tsx")
};
