// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/today-cards/GoalProgress.tsx": () => import("../components/mockups/today-cards/GoalProgress.tsx"),
  "./components/mockups/today-cards/Motivation.tsx": () => import("../components/mockups/today-cards/Motivation.tsx"),
  "./components/mockups/today-cards/Recovery.tsx": () => import("../components/mockups/today-cards/Recovery.tsx")
};
