import { pgTable, serial, text, timestamp, integer, jsonb, index } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { workoutSessionsTable } from "./workoutSessions";

// One summary per completed session, generated by Claude.
// keyFacts is a structured JSON object that gets merged into the user's
// workoutMemory field on their profile so Valo's voice context stays current.
export const workoutSummariesTable = pgTable("workout_summaries", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull(),
  // One-to-one with workout_sessions; cascade delete keeps history clean.
  sessionId: integer("session_id").notNull().unique().references(() => workoutSessionsTable.id, { onDelete: "cascade" }),
  summaryText: text("summary_text").notNull(),
  keyFacts: jsonb("key_facts")
    .$type<Record<string, unknown>>()
    .notNull()
    .default(sql`'{}'::jsonb`),
  memoryMergedAt: timestamp("memory_merged_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => [
  index("workout_summaries_user_id_idx").on(t.userId),
]);

export const insertWorkoutSummarySchema = createInsertSchema(workoutSummariesTable)
  .omit({ id: true, createdAt: true, updatedAt: true })
  .partial({ memoryMergedAt: true });

export type InsertWorkoutSummary = z.infer<typeof insertWorkoutSummarySchema>;
export type WorkoutSummary = typeof workoutSummariesTable.$inferSelect;
